name: build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull changes
        working-directory: ${{ vars.WORKING_DIR }}
        run: git pull origin master
      - name: Install dependencies
        working-directory: ${{ vars.WORKING_DIR }}
        run: python3 manager.py project install_deps
      - name: Build Bot
        working-directory: ${{ vars.WORKING_DIR }}
        run: python3 manager.py bot build_release
      - name: Build Task tracker
        working-directory: ${{ vars.WORKING_DIR }}
        run: python3 manager.py task_tracker build_release
      - name: Build containers
        working-directory: ${{ vars.WORKING_DIR }}
        run: docker compose build
  recreate_containers:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop containers
        working-directory: ${{ vars.WORKING_DIR }}
        run: docker compose stop -t 3
      - name: Remove containers
        working-directory: ${{ vars.WORKING_DIR }}
        run: docker compose rm -f
      - name: Up containers
        working-directory: ${{ vars.WORKING_DIR }}
        run: docker compose up -d
  